# Generated by Django 4.1.2 on 2022-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='available',
            field=models.IntegerField(default=10),
        ),
    ]
